### ISSUE TITLE
The zoom should be 0 in onInit.

### ISSUE THREAD

**Issue by nvtin** [deej81/ngx-croppie#18]
Hi @deej81 Thanks for your great component to integrate croppie library to angular.
I am using it to our project, and it is working well.
But it will be more great if the zoom of image should be 0 in onInit. In my project, the first time to show the image cropping, the zoom is not min. How can I set default is 0?

**Comment by nvtin** [comment]
@deej81 It's related https://github.com/deej81/ngx-croppie/pull/19

**Comment by deej81** [comment]
hopefully fixed by 2.1.0
