### ISSUE TITLE
Croppie.js version 2.6.3

### ISSUE THREAD

**Issue by edgarmkrtchyan** [deej81/ngx-croppie#25]
Hi,

Croppie.js released the version 2.6.3, but when I try to update my dev dependencies to update to it, I'm getting the "webpack imported module is not a constructor" error. Are there any plans to supporting this new version or any clues how this can be fixed?

Thanks.

**Comment by deej81** [comment]
I suspect they’ve fixed a bug they had with module imports, it’ll be very easy to fix and update the dependency requirements. I’ll take a look when I get back to a computer

**Comment by deej81** [comment]
if you need to get it working urgently the offending code will likely be here: https://github.com/deej81/ngx-croppie/blob/3fca67a9ab106250101d61ad97ed71b3bf447404/src/app/modules/ngx-croppie/ngx-croppie.component.ts#L36

**Comment by edgarmkrtchyan** [comment]
> if you need to get it working urgently the offending code will likely be here:
> 
> [ngx-croppie/src/app/modules/ngx-croppie/ngx-croppie.component.ts](https://github.com/deej81/ngx-croppie/blob/3fca67a9ab106250101d61ad97ed71b3bf447404/src/app/modules/ngx-croppie/ngx-croppie.component.ts#L36)
> 
> Line 36 in [3fca67a](/deej81/ngx-croppie/commit/3fca67a9ab106250101d61ad97ed71b3bf447404)
> 
>  this._croppie = new Croppie['Croppie'](this.imageEdit.nativeElement, this.croppieOptions);

Thanks. The breaking change which I can see is the following one:

Used to be:

`exports.Croppie = window.Croppie = Croppie;`

Changed to:

`return Croppie;`

**Comment by deej81** [comment]
try v.3.0.0 please, it's working for me.

**Comment by edgarmkrtchyan** [comment]
> try v.3.0.0 please, it's working for me.

Sorry, v.3.0.0 of what?

**Comment by deej81** [comment]
apologies I should have been more clear, I've released a fix as a major release incase anyone is stuck on croppie 2.6.2 or below. https://github.com/deej81/ngx-croppie/releases/tag/v3.0.0

**Comment by edgarmkrtchyan** [comment]
> apologies I should have been more clear, I've released a fix as a major release incase anyone is stuck on croppie 2.6.2 or below. https://github.com/deej81/ngx-croppie/releases/tag/v3.0.0

Thanks. The original error is gone. But now I'm getting this one:

**Comment by deej81** [comment]
I reproduce that unfortunately, I'll have to take when I have some more time. If you could share some steps to reproduce or some code showing the problem that would be really helpful.
