### ISSUE TITLE
Support croppie 2.6.1

### ISSUE THREAD

**Issue by gigadie** [deej81/ngx-croppie#5]
Hi,

I tried to see if using croppie 2.6.1 would fail, and it does. It would be cool if we could have support of the latest version of croppie in this fantastic component.

Thanks

**Comment by deej81** [comment]
Thanks for submitting an issue,what's the problem you get with 2.6.1? Could it be related to this https://github.com/Foliotek/Croppie/issues/470

**Comment by gigadie** [comment]
Hi,

Exactly, the problem is that.

**Comment by dklmuc** [comment]
Tried to get it working before my vacation 3 or 4 weeks ago and provide a PR for this, but no luck. So atm best way is to lock croppie version in packages.json to 2.5.1 and wait for https://github.com/Foliotek/Croppie/issues/470.

**Comment by deej81** [comment]
v1.0.0 supports 2.6 and above but unfortunately ONLY 2.6 and above. Considering what the fix was I'd also expect it to break again when they undo the change in the issue above

**Comment by dklmuc** [comment]
Nice work @deej81 👍 

If somebody is running into problems like:
`ERROR in node_modules/ngx-croppie/src/app/modules/ngx-croppie/ngx-croppie.component.d.ts(1,23): error TS2688: Cannot find type definition file for 'croppie'.`

make sure croppie typings are installed:
`npm i @types/croppie --save-dev`

**Comment by deej81** [comment]
Thanks @dklmuc I ran into that with the example and forgot to mention it. Going to close this issue now although I think the fix from the croppie team will come this week and break this again.
