### ISSUE TITLE
Error: Cannot find type definition file for 'croppie'.

### ISSUE THREAD

**Issue by MainaWycliffe** [deej81/ngx-croppie#9]
I am getting the following error when i try and build my project. 

ERROR in node_modules/ngx-croppie/src/app/modules/ngx-croppie/ngx-croppie.component.d.ts(1,23): error TS2688: Cannot find type definition file for 'croppie'.

When is remove the line it disappears.

**Comment by deej81** [comment]
Hi, you need to have the type definitions for croppie installed, you can install them by running this command:

`npm i @types/croppie --save-dev`

hope that solves the problem for you.

**Comment by MainaWycliffe** [comment]
Thanks. It works. Am closing this.
